### ISSUE TITLE
如何定位ini文件

### ISSUE THREAD

**Issue by SmmnaBeta** [Arathi/palworld-manager#2]
虽然但是我研究了半天我不会用呜呜呜

**Comment by Arathi** [comment]
看[官方文档](https://tech.palworldgame.com/optimize-game-balance)。

Windows下，配置文件在`steamapps\common\PalServer\Pal\Saved\Config\WindowsServer\PalWorldSettings.ini`。

Linux下，配置文件`steamapps/common/PalServer/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini`。

不过`steamapps`这个目录具体在哪里，你就得自己找了qnq
